---
# Adds local repository
  - name: Add local repository
    copy:
      src: ./config/apt_repo/sources.list
      dest: /etc/apt/sources.list
      mode: 0644

  - name: Copy apt repository public key
    copy:
      src: ./config/apt_repo/keys/ansible.pub
      dest: /root/ansible.pub
      mode: 0644

  - name: Add  apt repository public key
    shell: apt-key add /root/ansible.pub
